### ISSUE TITLE
Installation of shakemap failed

### ISSUE THREAD

**Issue by Jaguar101-jr** [DOI-USGS/ghsc-esi-shakemap#13]
Please describe your issue here:
I installed conda separately, after running the shell script in install.sh I got error as 
{Activating the shakemap virtual environment                                                             
############# Installing shakemap ##############                                                        
Obtaining file:///home/osboxes/shakemap/ghsc-esi-shakemap-main                                          
  Installing build dependencies ... done                                                                
  Checking if build backend supports build_editable ... done                                            
  Getting requirements to build editable ... error                                                      
  error: subprocess-exited-with-error                                                                   
                                                                                                        
  × Getting requirements to build editable did not run successfully.                                    
  │ exit code: 1                                                                                        
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "/home/osboxes/miniconda3/envs/shakemap/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/osboxes/miniconda3/envs/shakemap/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/osboxes/miniconda3/envs/shakemap/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 307, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 658, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 121, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-lxaktkn4/overlay/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /home/osboxes/shakemap/ghsc-esi-shakemap-main.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
Installation of shakemap failed.

}
What am I missing? My Linux OS Ubuntu LTS 16 is an image of a virtual box contains Madagascar and Seismic Un*x software with full python and other programming languages packages.

**Comment by cbworden-usgs** [comment]
It's not clear from your message what steps you took to install the repo or what else you are doing. I have never seen the errors you have reported. Please follow the installation instructions at:

https://code.usgs.gov/ghsc/esi/shakemap/-/wikis/Installation

**Comment by Jaguar101-jr** [comment]
Even me I'm bit confused cuz my Ubuntu OS is working well when I run SCons of Madacascar/Shell scipts of Seismic Un*x. But let me ask you one question please: does this repo of shakemap can be installed on Linux v16 or not?

**Comment by cbworden-usgs** [comment]
It's unclear. We only have resources to test ShakeMap on the systems available to us. We are running on Scientific Linux 7.9, Amazon Linux, and have at least one user running on Ubuntu 20.04.

**Comment by Jaguar101-jr** [comment]
Thank you sir for your comment. I tried to re-download the source code using this link [https://code.usgs.gov/ghsc/esi/shakemap](url) cuz my network cloning is slow on VirtualBox. I also, installed Ubuntu 20.04 OS instead of v.16 and installed all prerequisite packages and then run {bash install.sh} but still I get exactly the same error shown above. Furthermore, I also tried to change the setup directory from /Home into /Desktop but still receive the same error.
![Screenshot 2024-04-16 025313](https://github.com/DOI-USGS/ghsc-esi-shakemap/assets/62794321/e8f8185e-6a10-4f90-a9db-5097e989382f)
![Screenshot 2024-04-16 025328](https://github.com/DOI-USGS/ghsc-esi-shakemap/assets/62794321/93515a38-4194-4d19-8a7b-bd0d4f2a7271)
![Screenshot 2024-04-16 025859](https://github.com/DOI-USGS/ghsc-esi-shakemap/assets/62794321/f9258ff1-31c1-49b3-ba5f-ab3168b6fd5b)

**Comment by cbworden-usgs** [comment]
I can't reproduce this problem. From the error messages it looks like your virtual box is having trouble connecting to some external resource. "files.pythonhosted.org". From a quick google search it seems that this might be related to access to pypi.python.org. Make sure you can ping these. Some people also suggested adding --default-timeout=100 to the pip install command. You could modify install.sh to add that.

**Comment by Jaguar101-jr** [comment]
It works and had installed it finally. The main issue was that my university uses a 5G/4G network and it was restricted by your server despite I was using paid VPN services to tunnel the whole PC even the VB.  Now I'm stuck at the second step 'installing: [STREC]{(https://code.usgs.gov/ghsc/esi/strec)} and I believe the reason is the same.
